services:
  nginx:
    image: nginx:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=tu-dominio.com
      - LETSENCRYPT_HOST=tu-dominio.com
      - LETSENCRYPT_EMAIL=tu-email@ejemplo.com
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_mysql_password
      - DB_NAME=your_database_name
      - PORT=3000
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - proxy
      - backend-network
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_password
      - MYSQL_DATABASE=your_database_name
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy
    external: true
  backend-network:
    driver: bridge

volumes:
  mysql-data:
